blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/GeneticxCln/StreamGo/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/GeneticxCln/StreamGo/blob/main/README.md
    about: Read the documentation, setup guides, and FAQs
  - name: 🔒 Security Policy
    url: https://github.com/GeneticxCln/StreamGo/blob/main/SECURITY.md
    about: Review our security policy and responsible disclosure guidelines
