name: Security Vulnerability
description: Report a security vulnerability (use private reporting if available)
title: "[Security]: "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: Private Reporting Recommended
        
        For sensitive security issues, please DO NOT use this public form.
        Instead, report privately by:
        - Using GitHub's Private Security Reporting feature (if available)
        - Emailing the security contact listed in SECURITY.md
        
        Only use this form for:
        - Low-severity security improvements
        - Security-related feature requests
        - General security discussions

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe do you think this issue is?
      options:
        - Low - Security improvement suggestion
        - Medium - Minor security concern
        - High - Please report privately instead
        - Critical - Please report privately instead
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern or improvement
      placeholder: |
        Please provide a general description. 
        DO NOT include exploit details in public issues!
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Content Security Policy (CSP)
        - Input Validation
        - Authentication/Authorization
        - Dependency Vulnerability
        - Data Privacy
        - Network Security
        - Addon System Security
        - Code Injection
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this issue is exploited? (Keep it general)
      placeholder: This could potentially allow...
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix or mitigate this?
    validations:
      required: false

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of StreamGo are affected?
      placeholder: e.g., 0.1.0 and earlier
    validations:
      required: false

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Responsible Disclosure
      description: Please confirm your understanding
      options:
        - label: I understand that critical vulnerabilities should be reported privately
          required: true
        - label: I have read the SECURITY.md file
          required: true
        - label: This is a low-severity issue appropriate for public discussion
          required: true
